services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${BLUEPRINT_DB_DATABASE}
      POSTGRES_USER: ${BLUEPRINT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /app/openapi.yml
    volumes:
      - ./openapi.yml:/app/openapi.yml:ro

  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      PGWEB_DATABASE_URL: "postgres://${BLUEPRINT_DB_USERNAME}:${BLUEPRINT_DB_PASSWORD}@psql_bp:5432/${BLUEPRINT_DB_DATABASE}?sslmode=disable"
    depends_on:
      - psql_bp

volumes:
  psql_volume_bp:
