services:
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /app/openapi.yml
    volumes:
      - ./openapi.yml:/app/openapi.yml:ro

  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      PGWEB_DATABASE_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@psql:5432/${DB_DATABASE}?sslmode=disable"
    depends_on:
      - psql

volumes:
  psql_volume:
