name: Go Lint and Format

on:
  push:
    paths:
      - '**.go'

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Go環境をセットアップ
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: gofmt を実行
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files are not properly formatted:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: golangci-lintを実行
        env:
          GOFLAGS: "-buildvcs=false"
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m
